// ---------------------------------------------------------------------------
// SI Section 9 concession atlas -- layout template
//
// Data comes from atlas_data.typ, generated by write_atlas_data_typ() in
// R/06_si_concession_atlas.R. Compile via compile_concession_atlas(); the
// pipeline passes --root <repo root> so the absolute paths below resolve.
//
// Typography matches the Word SI: Palatino, 13 pt bold section heading
// (Heading2), 11 pt body (Normal), 9 pt index (Caption size).
// ---------------------------------------------------------------------------

#import "/outputs/atlas/atlas_data.typ": tiles, groups, ungrouped_count

// Page numbering continues the Word-exported SI rather than restarting at 1.
// The merge script passes the SI's real page count; pipeline builds pass 0.
#let sm-pages = int(sys.inputs.at("sm-pages", default: "0"))

#let palatino = (
  "Palatino Linotype", // Windows -- identical outlines to the Word file
  "Palatino",          // macOS
  "Book Antiqua",
  "TeX Gyre Pagella",  // Linux / Docker (fonts-texgyre)
  "URW Palladio L",
)

#set text(font: palatino, size: 11pt, lang: "en")
#set par(justify: false)
#set heading(numbering: none)

// Tile labels are level-2 headings: one construct gives the visible label, the
// index entry, the link target and the PDF bookmark.
#show heading.where(level: 2): it => block(
  above: 0pt,
  below: 3.5pt,
  text(size: 7.5pt, weight: "bold", fill: black, it.body),
)
#show heading.where(level: 1): it => block(
  above: 0pt,
  below: 10pt,
  text(size: 13pt, weight: "bold", fill: black, it.body),
)

// --- shared legend -------------------------------------------------------
#let swatch(colour, label) = box(baseline: 0pt)[
  #box(fill: rgb(colour), width: 9pt, height: 5pt, radius: 0.5pt)
  #h(2.5pt)
  #text(size: 7.5pt, label)
]

#let rule-key(dash, label) = box(baseline: 0pt)[
  #box(width: 10pt, height: 5pt)[
    #place(
      center + horizon,
      line(length: 10pt, stroke: (paint: black, thickness: 0.7pt, dash: dash)),
    )
  ]
  #h(2.5pt)
  #text(size: 7.5pt, label)
]

#let atlas-legend = box[
  #swatch("#009E73", "Forest")
  #h(9pt)
  #swatch("#F0E442", "Non-forest")
  #h(9pt)
  #swatch("#CC79A7", "Pulpwood plantation")
  #h(9pt)
  #rule-key("solid", "Earliest ZDC year of downstream mill")
  #h(9pt)
  #rule-key("dashed", "License year")
  #h(9pt)
  #text(size: 7.5pt, style: "italic")[Areas in hectares]
]

#let folio = context text(size: 8pt, counter(page).display("1"))

// --- page setup ----------------------------------------------------------
// Front matter and index: folio only.
#set page(
  paper: "us-letter",
  margin: 1in,
  footer: align(center, folio),
)
#counter(page).update(sm-pages + 1)

// --- front matter --------------------------------------------------------
= 9. Supplementary figures: concession atlas

#set par(leading: 1.45em, spacing: 1.45em)

Based on our analyses of deforestation and pulpwood plantation expansion, we are
able to track changes in land cover since 2000 within each individual pulpwood
concession. The figures in this atlas visualize these changes for each of the
#tiles.len() pulpwood concessions in our database, breaking land cover into
(a) areas that are still forested (green); (b) areas that have been deforested
but were not immediately converted to pulpwood plantations (yellow); and
(c) areas that were converted into pulpwood plantations (pink). In addition, we
provide contextual information detailing the year in which each concession was
first licensed, as well as the year in which any downstream buyers first enacted
a zero-deforestation commitment (ZDC).

#set par(leading: 0.75em, spacing: 0.9em)

#block(above: 18pt, below: 12pt)[
  #text(size: 11pt, weight: "bold")[How to read these figures]

  #set text(size: 10pt)
  - Concessions are ordered by concession license identifier (H-\#\#\#\#). Use the
    index on the following pages to jump to a particular concession.
  - If the license year is missing from a concession's plot, the concession
    license was granted prior to 2001. If the ZDC year is missing, the
    concession has not yet started supplying any downstream pulp mill.
  - Vertical axes are labelled in hectares; horizontal axes run from 2001 to
    2022.
  - Each concession is labelled with its island and, where one is identified,
    its parent corporate group. Most concessions have no named parent group:
    they are independent or third-party suppliers.
]

#block(
  width: 100%,
  inset: 6pt,
  stroke: 0.4pt + luma(70%),
  radius: 1pt,
  align(center, atlas-legend),
)

// --- index ---------------------------------------------------------------
#pagebreak()

= Index of concessions

#columns(2, gutter: 0.3in)[
  #set text(size: 9pt)
  #set par(leading: 0.55em, spacing: 0.55em)
  #outline(title: none, target: heading.where(level: 2), depth: 2)
]

// --- secondary index by corporate group ----------------------------------
#pagebreak()

= Index by corporate group

#block(above: 0pt, below: 8pt, text(size: 9pt, style: "italic")[
  Concessions affiliated with a named corporate group, largest affiliation
  first. The remaining #ungrouped_count concessions are not affiliated with a
  named corporate group.
])

#columns(2, gutter: 0.3in)[
  #set text(size: 9pt)
  #set par(leading: 0.55em, spacing: 0.55em)
  #for grp in groups [
    #block(above: 6pt, below: 3pt, text(weight: "bold", grp.name))
    #for e in grp.entries [
      #box(width: 100%)[
        #link(label("c" + e.id))[#e.id #h(3pt) #e.name]
        #box(width: 1fr, repeat(text(fill: luma(60%))[.]))
        #h(3pt)
        #context counter(page).at(locate(label("c" + e.id))).first()
      ] \
    ]
  ]
]

// --- figure pages --------------------------------------------------------
#pagebreak()

// From here the shared legend runs in the footer of every page, so a reader
// landing anywhere in the atlas always has the full key in view.
#set page(
  footer: {
    align(center, atlas-legend)
    v(2pt)
    align(center, folio)
  },
)

#let meta-line(t) = {
  let parts = ()
  if t.island != "" { parts.push(t.island) }
  if t.group != "" { parts.push(t.group) }
  let shown = if parts.len() == 0 { "—" } else { parts.join(" · ") }
  block(above: 0pt, below: 3pt, text(size: 7pt, style: "italic", fill: luma(40%), shown))
}

// The label occupies a fixed height so every tile's image starts at the same
// offset. Names are shortened upstream (former-name parentheticals dropped) and
// set at 7.5 pt, at which all 305 fit on one line with ~9 pt to spare.
#let tile-block(t) = block(breakable: false, width: 100%)[
  #block(width: 100%, height: 24pt, above: 0pt, below: 0pt)[
    #heading(level: 2, outlined: true, bookmarked: true)[#t.id #h(5pt) #t.name]
    #label("c" + t.id)
    #meta-line(t)
  ]
  #image(t.file, width: 100%)
]

// Rows are 1fr so the ~0.4 in of intrinsic slack (a two-column grid of 4:3
// tiles is width-limited) is distributed between rows rather than pooling as
// dead space at the foot of the page.
#for page-tiles in tiles.chunks(6) {
  block(
    width: 100%,
    height: 100%,
    grid(
      columns: (1fr, 1fr),
      rows: (1fr, 1fr, 1fr),
      column-gutter: 0.28in,
      row-gutter: 0.26in,
      ..page-tiles.map(t => tile-block(t)),
    ),
  )
  pagebreak(weak: true)
}
